modified for linux and added list-remove methods
mdfind is replaced with find
-r and -l options added to remove and list notes in notes directory

diff --git a/qq b/qq
--- a/qq
+++ b/qq
@@ -1,74 +1,85 @@
 #!/bin/bash
 
 # notes folder, for note creation and limiting searches
-NOTESDIR="/Volumes/Raptor/Users/ttscoff/Dropbox/nvALT2.2"
+NOTESDIR="/home/cagriemer/.notes"
 # extension used for your notes
-NOTESEXT="md"
+# example NOTESEXT=".md"
+NOTESEXT=""
 # the prefix you use to separate "Question" notes
-NOTESPRE="??"
+NOTESPRE=""
 # editor command to use for modifying answers
-EDITOR="subl"
+EDITOR="nano"
 
 NOTESDIR=`echo $NOTESDIR|sed -e '/\/$/! s/$/\//'`
 
 if [[ "$1" == "-h" ]]
 then
-  appname=`basename $0`
+appname=`basename $0`
   echo "$appname: build a knowledgebase with plain text files"
   echo "Find an answer: $appname \"terms to search for\""
   echo "Add a question\answer: $appname -a \"Question in natural language\" \"Succinct answer\""
   echo "Add a question\answer interactively: $appname -a"
   echo "Edit a question\answer: $appname -e \"terms to search for\" # first question found is edited"
+
+elif [[ "$1" = "-l" ]]
+then
+ls -t1 $NOTESDIR | nl
+elif [[ "$1" = "-r" ]]
+then
+shift
+INPUT=$@
+find "$NOTESDIR" -name "$INPUT" -exec rm -rf {} \;
 elif [[ "$1" == "-a" ]]
 then
-  if [ $# == 3 ]; then
-    QUESTION=$2
+if [ $# == 3 ]; then
+QUESTION=$2
     ANSWER=$3
   elif [ $# == 1 ]; then
-    echo -n "Question: "
+echo -n "Question: "
     read QUESTION
     echo -n "Answer: "
     read ANSWER
   else
-    echo "Invalid number of arguments for -a(dd). Requires question and answer (or no arguments to input them at runtime)."
+echo "Invalid number of arguments for -a(dd). Requires question and answer (or no arguments to input them at runtime)."
     echo "example: ${0##*/} -a \"What is the meaning of life?\" \"42\""
     exit 1
   fi
-  echo -n "$ANSWER" > "${NOTESDIR}$NOTESPRE $QUESTION.$NOTESEXT" && echo "Question added and answered." || echo "Something went wrong"
+echo -n "$ANSWER" > "$NOTESDIR$NOTESPRE$QUESTION$NOTESEXT" && echo "Question added and answered." || echo "Something went wrong"
 elif [[ "$1" == "-e" ]]; then
-  shift
-  INPUT=$@
-  ANSWER=`mdfind -onlyin "$NOTESDIR" "filename:.$NOTESEXT AND filename:\"$NOTESPRE\" AND ${INPUT%\?}"|head -n 1`
+shift
+INPUT=$@
+  ANSWER=`find "$NOTESDIR" -name "$INPUT"|head -n 1`
   if [[ "$ANSWER" == "" ]]; then
-    echo "No results found for search."
+echo "No results found for search."
     exit 2
   else
     $EDITOR "$ANSWER"
   fi
 else
-  INPUT=$@
-  echo "`mdfind -onlyin \"$NOTESDIR\" -interpret \"filename:.$NOTESEXT AND filename:$NOTESPRE AND ${INPUT%\?}\"`"|while read LINE; do
-      if [[ "$LINE" == "" ]]; then
-        echo "Sorry, I don't know the answer to that question."
+INPUT=$@
+  echo "`find "$NOTESDIR" -name "$INPUT"`"|while read LINE; do
+if [[ "$LINE" == "" ]]; then
+echo "Sorry, I don't know the answer to that question."
         exit 1;
       fi
-      QUESTION=${LINE##*/}
+QUESTION=${LINE##*/}
       echo -n "Q: "
       NOTESPREESC=`echo "$NOTESPRE"|sed -E 's/([\?\!\$\`\"]) ?/\\\\\1/g'`
-      echo ${QUESTION%%.$NOTESEXT}|sed -E "s/$NOTESPREESC ?//g"|sed -E 's/(.)$/\1?/'
+#      echo ${QUESTION%%$NOTESEXT}|sed -E "s/$NOTESPREESC ?//g"|sed -E 's/(.)$/\1?/'
+      echo $QUESTION
       echo -n "A: "
-      cat "$LINE"|sed -E 's/@\([^\)]+\) ?//g'|sed -E 's/@copy\(([^)]*)\)/\1/'|sed -E 's/@open\(([^)]*)\)/Related URL: \1/'|sed -E 's/^[   ]*|[  ]*$//g'
+      cat "$LINE"|sed -E 's/@\([^\)]+\) ?//g'|sed -E 's/@copy\(([^)]*)\)/\1/'|sed -E 's/@open\(([^)]*)\)/Related URL: \1/'|sed -E 's/^[ ]*|[ ]*$//g'
       if [[ `cat "$LINE"|grep -E '@copy\('` ]]; then
-        cat "$LINE"|grep '@copy('|sed -E 's/.*@copy\(([^)]*)\).*/\1/'|tr -d '\n'|pbcopy
-        echo "Example in clipboard"
+cat "$LINE"|grep '@copy('|sed -E 's/.*@copy\(([^)]*)\).*/\1/'|tr -d '\n'|xclip -selection clipboard
+        echo -e "\nExample in clipboard"
       fi
 
-      if [[ `cat "$LINE"|grep -E '@open\('` ]]; then
-        url=$(cat "$LINE"|grep '@open('|sed -E 's/.*@open\(([^)]*)\).*/\1 /'|tr -d '\n')
-        open -g $url
-        echo "Opened URL"
+if [[ `cat "$LINE"|grep -E '@open\('` ]]; then
+url=$(cat "$LINE"|grep '@open('|sed -E 's/.*@open\(([^)]*)\).*/\1 /'|tr -d '\n')
+        firefox -new-window $url
+        echo -e "\nOpened URL"
       fi
-      echo
-  done
+echo
+done
 fi
 exit 0
